### ISSUE TITLE
`save-if` doesn't seem to work right

### ISSUE THREAD

**Issue by ilyvion** [Leafwing-Studios/cargo-cache#43]
I have this step in my CI:
```yaml
- name: Cache the Cargo build files
    uses: Leafwing-Studios/cargo-cache@v2
    with:
        cache-group: ubuntu-latest-stable
        save-if: github.event_name != 'pull_request'
```
but despite being run not as a pull request[^napr], the output was just
```
Post job cleanup.
```
By comparision, a run without a `save-if` produces output like
```
Post job cleanup.
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/bevy_image_font/bevy_image_font --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~271 MB (283870954 B)
Cache saved successfully
Cache saved with key: [...]
```

[^napr]: I know it wasn't accidentally a pull request because a step that uses an `if` with the exact same predicate (i.e. `if: github.event_name != 'pull_request'`) was run, meaning the predicate is, in fact, `true`.

**Comment by BD103** [comment]
> I have this step in my CI:
> 
> ```yml
> - name: Cache the Cargo build files
>   uses: Leafwing-Studios/cargo-cache@v2
>   with:
>     cache-group: ubuntu-latest-stable
>     save-if: github.event_name != 'pull_request'
> ```

I believe I know what's wrong. `save-if` isn't preprocessed by Github[^0], so it's treated as a string. I believe the following is equivalent to what you have:

```yml
- name: Cache the Cargo build files
  uses: Leafwing-Studios/cargo-cache@v2
  with:
    cache-group: ubuntu-latest-stable
    # That's a string!
    save-if: "github.event_name != 'pull_request'"
```

Could you try using this instead, and let me know if it works?

```yml
- name: Cache the Cargo build files
  uses: Leafwing-Studios/cargo-cache@v2
  with:
    cache-group: ubuntu-latest-stable
    # Make Github Actions evaluate this expression into 'true' or 'false'.
    save-if: ${{ github.event_name != 'pull_request' }}
```

[^0]: What's silly about this is that Github **does** preprocess `if`. See [the docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif):

      > "When you use expressions in an `if` conditional, you can, optionally, omit the `${{ }}` expression syntax because GitHub Actions automatically evaluates the `if` conditional as an expression. However, this exception does not apply everywhere."
